server:
  port: 8090
work-home: C:\代码批量管理
logging:
  file:
    path: ${work-home}\logs
modules-home: ${work-home}\modules
git-username:
git-password:
projects:
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/core-components/geostack-parent.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/core-components/geostack-3rd-framework.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/drive/common/geostack-cloud-parent.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/core-components/geostack-manager-parent.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/core-components/GeoCloudActiveMQClient.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/core-components/geostack-monitor-center-client.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/core-components/geostack-test.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/drive/container/geostack-docker-engine-api.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/drive/common/geostack-cloud-common.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/drive/cloud/geostack-cloud-cloudstack.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/drive/container/geostack-docker-api.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/drive/container/geostack-cloud-docker.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/drive/container/geostack-cloud-libvirt.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/drive/cloud/geostack-ucloud-api.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/drive/cloud/geostack-manageone-api.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/drive/cloud/geostack-manageone-api6.3.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/drive/cloud/geostack-manageone-api6.5.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/zabbix/geostack-spark-api.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/drive/cloud/geostack-cloud-ucloud.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/drive/cloud/geostack-cloud-manageone.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/drive/cloud/geostack-cloud-manageone6.3.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/drive/cloud/geostack-cloud-manageone6.5.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/drive/cloud/geostack-openstack-limits.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/drive/cloud/geostack-openstack-serverinfo.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/drive/cloud/geostack-cloud-openstack.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/core-components/geostack-framework.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/core-components/geostack-processfactory.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/core-components/geostack-quartz.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/core-components/geostack-log.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/core-components/geostack-es-monitor-api.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/zabbix/geostack-zabbix-api.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/zabbix/geostack-monitor-common.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/zabbix/geostack-monitor-zabbix.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/zabbix/geostack-zabbix.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/usersystem/Usersystem.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/core-components/geostack-dictionary.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/core-components/geostack-portal.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/core-components/geostack-dependence.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/core-components/geostack-balance-core.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/core-components/geostack-balance-haproxy.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/soms/geostack-soms.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/core-components/geostack-orders-resolve.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/core-components/geostack-dispatch.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/core-components/geostack-telescopic.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/core-components/geostack-core.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/core-components/geostack-databasegoods.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/core-components/geostack-gistools.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/core-components/geostack-servicegoods.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/core-components/geostack-proxy.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/core-components/geostack-topology.git
  - http://xc-gitlab.geostar.com.cn/geostack-source/cloud-platform/web-application/OperationCenter.git
