spring:
  thymeleaf:
    prefix: classpath:/templates/
  config:
    import:
      - classpath:/application-git.yml
server:
  port: 8090
work-home: xxxxxx
git-save-location: /xxxxxx/src/main/resources/application-git.yml
logging:
  file:
    path: ${work-home}\logs
modules-home: ${work-home}\modules