projects:
 - https://e.coding.net/baiguokeji/DIEPORDERN/dm-order.git
 - https://e.coding.net/baiguokeji/DIEPORDERN/dm-order-info.git
 - https://e.coding.net/baiguokeji/DIEPORDERN/sdk-order.git
 - https://e.coding.net/baiguokeji/DIEPORDERN/ms-order-mqconsumer.git
 - https://e.coding.net/baiguokeji/DIEPORDERN/ms-order-crm.git
